import { CountryData } from "@/types/energy";

export const COUNTRIES: Record<string, CountryData> = {
  AT: {
    code: "AT",
    name: "Austria",
    flag: "\u{1F1E6}\u{1F1F9}",
    eicCode: "10YAT-APG------L",
    centroid: [14.55, 47.52],
  },
  BE: {
    code: "BE",
    name: "Belgium",
    flag: "\u{1F1E7}\u{1F1EA}",
    eicCode: "10YBE----------2",
    centroid: [4.47, 50.5],
  },
  BG: {
    code: "BG",
    name: "Bulgaria",
    flag: "\u{1F1E7}\u{1F1EC}",
    eicCode: "10YCA-BULGARIA-R",
    centroid: [25.49, 42.73],
  },
  CH: {
    code: "CH",
    name: "Switzerland",
    flag: "\u{1F1E8}\u{1F1ED}",
    eicCode: "10YCH-SWISSGRIDZ",
    centroid: [8.23, 46.82],
  },
  CZ: {
    code: "CZ",
    name: "Czech Republic",
    flag: "\u{1F1E8}\u{1F1FF}",
    eicCode: "10YCZ-CEPS-----N",
    centroid: [15.47, 49.82],
  },
  DE: {
    code: "DE",
    name: "Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
    eicCode: "10Y1001A1001A83F",
    centroid: [10.45, 51.17],
  },
  DK1: {
    code: "DK1",
    name: "Denmark West",
    flag: "\u{1F1E9}\u{1F1F0}",
    eicCode: "10YDK-1--------W",
    centroid: [9.5, 56.26],
  },
  DK2: {
    code: "DK2",
    name: "Denmark East",
    flag: "\u{1F1E9}\u{1F1F0}",
    eicCode: "10YDK-2--------M",
    centroid: [12.0, 55.68],
  },
  EE: {
    code: "EE",
    name: "Estonia",
    flag: "\u{1F1EA}\u{1F1EA}",
    eicCode: "10Y1001A1001A39I",
    centroid: [25.01, 58.6],
  },
  ES: {
    code: "ES",
    name: "Spain",
    flag: "\u{1F1EA}\u{1F1F8}",
    eicCode: "10YES-REE------0",
    centroid: [-3.75, 40.46],
  },
  FI: {
    code: "FI",
    name: "Finland",
    flag: "\u{1F1EB}\u{1F1EE}",
    eicCode: "10YFI-1--------U",
    centroid: [25.75, 61.92],
  },
  FR: {
    code: "FR",
    name: "France",
    flag: "\u{1F1EB}\u{1F1F7}",
    eicCode: "10YFR-RTE------C",
    centroid: [2.21, 46.23],
  },
  GR: {
    code: "GR",
    name: "Greece",
    flag: "\u{1F1EC}\u{1F1F7}",
    eicCode: "10YGR-HTSO-----Y",
    centroid: [21.82, 39.07],
  },
  HR: {
    code: "HR",
    name: "Croatia",
    flag: "\u{1F1ED}\u{1F1F7}",
    eicCode: "10YHR-HEP------M",
    centroid: [15.98, 45.1],
  },
  HU: {
    code: "HU",
    name: "Hungary",
    flag: "\u{1F1ED}\u{1F1FA}",
    eicCode: "10YHU-MAVIR----U",
    centroid: [19.5, 47.16],
  },
  IE: {
    code: "IE",
    name: "Ireland",
    flag: "\u{1F1EE}\u{1F1EA}",
    eicCode: "10Y1001A1001A59C",
    centroid: [-8.24, 53.41],
  },
  IT_N: {
    code: "IT_N",
    name: "Italy North",
    flag: "\u{1F1EE}\u{1F1F9}",
    eicCode: "10Y1001A1001A73I",
    centroid: [11.0, 45.0],
  },
  LT: {
    code: "LT",
    name: "Lithuania",
    flag: "\u{1F1F1}\u{1F1F9}",
    eicCode: "10YLT-1001A0008Q",
    centroid: [23.88, 55.17],
  },
  LV: {
    code: "LV",
    name: "Latvia",
    flag: "\u{1F1F1}\u{1F1FB}",
    eicCode: "10YLV-1001A00074",
    centroid: [24.6, 56.88],
  },
  NL: {
    code: "NL",
    name: "Netherlands",
    flag: "\u{1F1F3}\u{1F1F1}",
    eicCode: "10YNL----------L",
    centroid: [5.29, 52.13],
  },
  NO1: {
    code: "NO1",
    name: "Norway South",
    flag: "\u{1F1F3}\u{1F1F4}",
    eicCode: "10YNO-1--------2",
    centroid: [10.0, 60.0],
  },
  NO2: {
    code: "NO2",
    name: "Norway Southwest",
    flag: "\u{1F1F3}\u{1F1F4}",
    eicCode: "10YNO-2--------T",
    centroid: [6.0, 59.0],
  },
  PL: {
    code: "PL",
    name: "Poland",
    flag: "\u{1F1F5}\u{1F1F1}",
    eicCode: "10YPL-AREA-----S",
    centroid: [19.15, 51.92],
  },
  PT: {
    code: "PT",
    name: "Portugal",
    flag: "\u{1F1F5}\u{1F1F9}",
    eicCode: "10YPT-REN------W",
    centroid: [-8.22, 39.4],
  },
  RO: {
    code: "RO",
    name: "Romania",
    flag: "\u{1F1F7}\u{1F1F4}",
    eicCode: "10YRO-TEL------P",
    centroid: [24.97, 45.94],
  },
  RS: {
    code: "RS",
    name: "Serbia",
    flag: "\u{1F1F7}\u{1F1F8}",
    eicCode: "10YCS-SERBIATSOV",
    centroid: [21.01, 44.02],
  },
  SE1: {
    code: "SE1",
    name: "Sweden North",
    flag: "\u{1F1F8}\u{1F1EA}",
    eicCode: "10Y1001A1001A44P",
    centroid: [18.0, 66.0],
  },
  SE3: {
    code: "SE3",
    name: "Sweden Central",
    flag: "\u{1F1F8}\u{1F1EA}",
    eicCode: "10Y1001A1001A46L",
    centroid: [16.0, 59.33],
  },
  SE4: {
    code: "SE4",
    name: "Sweden South",
    flag: "\u{1F1F8}\u{1F1EA}",
    eicCode: "10Y1001A1001A47J",
    centroid: [14.0, 56.0],
  },
  SI: {
    code: "SI",
    name: "Slovenia",
    flag: "\u{1F1F8}\u{1F1EE}",
    eicCode: "10YSI-ELES-----O",
    centroid: [14.99, 46.15],
  },
  SK: {
    code: "SK",
    name: "Slovakia",
    flag: "\u{1F1F8}\u{1F1F0}",
    eicCode: "10YSK-SEPS-----K",
    centroid: [19.7, 48.67],
  },
  GB: {
    code: "GB",
    name: "United Kingdom",
    flag: "\u{1F1EC}\u{1F1E7}",
    eicCode: "10YGB----------A",
    centroid: [-1.17, 52.36],
  },
};

/** Map from ISO 3166-1 alpha-3 (TopoJSON) to our country code. */
export const ISO_A3_TO_CODE: Record<string, string> = {
  AUT: "AT",
  BEL: "BE",
  BGR: "BG",
  CHE: "CH",
  CZE: "CZ",
  DEU: "DE",
  DNK: "DK1",
  EST: "EE",
  ESP: "ES",
  FIN: "FI",
  FRA: "FR",
  GRC: "GR",
  HRV: "HR",
  HUN: "HU",
  IRL: "IE",
  ITA: "IT_N",
  LTU: "LT",
  LVA: "LV",
  NLD: "NL",
  NOR: "NO1",
  POL: "PL",
  PRT: "PT",
  ROU: "RO",
  SRB: "RS",
  SWE: "SE3",
  SVN: "SI",
  SVK: "SK",
  GBR: "GB",
};

/** Country pairs with known cross-border flows. */
export const FLOW_PAIRS: [string, string][] = [
  ["DE", "PL"],
  ["DE", "CZ"],
  ["DE", "AT"],
  ["DE", "NL"],
  ["DE", "FR"],
  ["DE", "DK1"],
  ["DE", "CH"],
  ["FR", "ES"],
  ["FR", "BE"],
  ["FR", "CH"],
  ["FR", "IT_N"],
  ["FR", "GB"],
  ["PL", "CZ"],
  ["PL", "SK"],
  ["PL", "SE4"],
  ["PL", "LT"],
  ["CZ", "SK"],
  ["CZ", "AT"],
  ["AT", "HU"],
  ["AT", "SI"],
  ["AT", "CH"],
  ["AT", "IT_N"],
  ["HU", "SK"],
  ["HU", "RO"],
  ["HU", "HR"],
  ["HU", "RS"],
  ["NL", "BE"],
  ["NL", "GB"],
  ["NO1", "SE3"],
  ["NO2", "DK1"],
  ["SE4", "DK2"],
  ["SE3", "FI"],
  ["EE", "FI"],
  ["EE", "LV"],
  ["LV", "LT"],
  ["ES", "PT"],
  ["BG", "RO"],
  ["BG", "GR"],
  ["HR", "SI"],
  ["RS", "RO"],
  ["RS", "BG"],
];

export const COUNTRY_LIST = Object.values(COUNTRIES).sort((a, b) =>
  a.name.localeCompare(b.name)
);
